# Photo source list (curated from the crew's processed shots, repo photos and video stills).
# (source key, caption, job, finished?)
def drv(n):
    return 'd:' + n
R, W_, L = 'rvpad-dsc0', 'walk-dsc0', 'crew-dsc0'
NEW = [
 # flagstone walkway, pro photos
 (drv(W_+'3930'), 'Finished flagstone walkway with chopped stone borders and path lights', 'walkway', 1),
 (drv(W_+'3953'), 'Flagstone walkway leading to the back porch', 'walkway', 1),
 (drv(W_+'3940'), 'Flagstone path curving out to the shed', 'walkway', 1),
 (drv(W_+'3950'), 'Path light along the new flagstone walkway', 'walkway', 1),
 (drv(W_+'3945'), 'Chopped stone border along the flagstone walkway', 'walkway', 1),
 (drv('walk-799673222_1633958414999902_1379811027983912017_n'), 'Flagstone walkway from the drive to the house', 'walkway', 1),
 (drv('walk-812223771_1812277616618072_2837960169825854401_n'), 'Front porch and new flagstone walk', 'walkway', 1),
 (drv(W_+'3576'), 'Walkway laid out and excavated', 'walkway', 0),
 (drv(W_+'3570'), 'Compacting the walkway base', 'walkway', 0),
 (drv(W_+'3580'), 'Spreading base gravel for the walkway', 'walkway', 0),
 (drv(W_+'3595'), 'Raking the base level', 'walkway', 0),
 (drv(W_+'3607'), 'Chopped stone staged for the borders', 'walkway', 0),
 (drv(W_+'3617'), 'Setting chopped stone border blocks', 'walkway', 0),
 (drv(W_+'3627'), 'Mixing mortar for the stone borders', 'walkway', 0),
 (drv(W_+'3688'), 'Shaping chopped stone with a hammer and chisel', 'walkway', 0),
 (drv(W_+'3698'), 'Setting a border stone by hand', 'walkway', 0),
 (drv(W_+'3710'), 'Two-man crew setting the stone border', 'walkway', 0),
 (drv(W_+'3744'), 'Stone borders running the length of the walk', 'walkway', 0),
 (drv(W_+'3778'), 'Track loader dumping base between the borders', 'walkway', 0),
 (drv(W_+'3811'), 'Moving base with the track loader', 'walkway', 0),
 (drv(W_+'3818'), 'Loader spreading base, dust flying', 'walkway', 0),
 (drv(W_+'3861'), 'Fitting flagstone along the border', 'walkway', 0),
 (drv(W_+'3873'), 'Setting flagstone on the walkway', 'walkway', 0),
 (drv(W_+'3886'), 'Chopped stone border, close up', 'walkway', 0),
 (drv(W_+'3893'), 'Plate compactor on the walkway', 'walkway', 0),
 # boat & RV pad, pro photos
 (drv(R+'3563'), 'Finished boat and RV pad with timber wall and gravel', 'rvpad', 1),
 (drv(R+'3562'), 'Level gravel pad ready for the boat and RV', 'rvpad', 1),
 (drv(R+'3085'), 'Timber wall lined up along the pad edge', 'rvpad', 1),
 (drv(R+'3224'), 'Pad filled and compacted inside the timber wall', 'rvpad', 1),
 (drv(R+'3043'), 'First timber set along the pad edge', 'rvpad', 0),
 (drv(R+'3046'), 'Cutting pressure-treated timbers', 'rvpad', 0),
 (drv(R+'3062'), 'Timber wall running down the pad line', 'rvpad', 0),
 (drv(R+'3066'), 'Leveling the timbers', 'rvpad', 0),
 (drv(R+'3074'), 'Dump truck and timbers on site', 'rvpad', 0),
 (drv(R+'3090'), 'Hauling timbers with the track loader', 'rvpad', 0),
 (drv(R+'3105'), 'Standing a timber into place', 'rvpad', 0),
 (drv(R+'3112'), 'Setting the next course of timbers', 'rvpad', 0),
 (drv(R+'3120'), 'Pad laid out in the backyard', 'rvpad', 0),
 (drv(R+'3124'), 'Fabric down and fill going in', 'rvpad', 0),
 (drv(R+'3129'), 'Track loader spreading fill', 'rvpad', 0),
 (drv(R+'3152'), 'Loader dumping fill inside the wall', 'rvpad', 0),
 (drv(R+'3158'), 'Crew working alongside the loader', 'rvpad', 0),
 (drv(R+'3174'), 'Drainage fabric along the timber wall', 'rvpad', 0),
 (drv(R+'3204'), 'Raking fill level', 'rvpad', 0),
 (drv(R+'3273'), 'Loader dropping gravel on the pad', 'rvpad', 0),
 (drv(R+'3290'), 'Raking gravel across the pad', 'rvpad', 0),
 (drv(R+'3428'), 'Gravel pouring from the bucket', 'rvpad', 0),
 (drv(R+'3508'), 'Final rake along the timber wall', 'rvpad', 0),
 # lawn crew, pro photos
 (drv(L+'4063'), 'Stand-on mower on a front yard route', 'lawn', 1),
 (drv(L+'4076'), 'Mowing a backyard', 'lawn', 1),
 (drv(L+'3988'), 'Stand-on mower cutting a lawn', 'lawn', 0),
 (drv(L+'4038'), 'String trimming the yard edges', 'lawn', 0),
 (drv(L+'4059'), 'Edging along the walk', 'lawn', 0),
 (drv(L+'4101'), 'Mowing the side yard', 'lawn', 0),
 (drv(L+'4152'), 'Trimming along the house', 'lawn', 0),
 (drv(L+'4179'), 'Blowing off clippings', 'lawn', 0),
 (drv(L+'4197'), 'Blowing off the driveway', 'lawn', 0),
]
OLD = [
 ('white-oak-flagstone-patio-after', 'Cherokee flagstone patio and chopped stone fire pit', 'whiteoak', 1),
 ('driveway-retaining-wall-after', 'Curved block wall stepping past the shop with a flagstone landing', 'driveway', 1),
 ('checkerboard-paver-patio-after', 'Checkerboard paver patio off a covered porch', 'checker', 1),
 ('front-roses-after', 'Knockout roses and boxwoods with sandstone edging', 'beds', 1),
 ('img-3738', 'Curved river rock bed with sandstone edging', 'more', 1),
 ('lighting-after', 'Foundation beds with landscape lighting at night', 'lighting', 1),
 ('retaining-wall-wood-to-block-east-texas-finished', 'Capped block retaining wall along a fence', 'woodwall', 1),
 ('backyard-firepit-after', 'Flagstone patio and fire pit at sunset', 'more', 1),
 ('img-3525', 'Flagstone walk with a low block wall', 'more', 1),
 ('deck-after', 'Curved bed along the deck', 'beds', 1),
 ('img-3737', 'Flagstone landing up to a slat deck', 'more', 1),
 ('flagstone-patio-after', 'Flagstone patio with a stone border', 'flagstone', 1),
 ('8', 'Freshly striped lawn', 'lawn', 1),
 ('driveway-retaining-wall-finished', 'Block wall and gravel drain strip along a driveway', 'driveway', 1),
 ('img-3523', 'Flagstone patio at the back door', 'more', 1),
 ('side-hydrangeas-after', 'Hydrangea bed with new edging', 'beds', 1),
 ('img-3526', 'Stepping stones past roses and boxwoods', 'more', 1),
 ('6', 'Flagstone walk between block walls', 'more', 1),
 ('4', 'Flagstone path along a white house', 'more', 1),
 ('back-fence-after', 'Mulched bed along the back fence', 'beds', 1),
 ('img-3736', 'River rock drainage strip', 'more', 1),
 ('3', 'Clean front beds and fresh-cut bermuda', 'more', 1),
 ('retaining-wall-wood-to-block-east-texas-after', 'Block retaining wall with capstones and a drain strip', 'woodwall', 1),
 ('12', 'Striped lawn at golden hour', 'lawn', 1),
 ('5', 'Dianthus in a fresh bed', 'more', 1),
 ('11', 'Roofline Christmas lights', 'more', 1),
 ('design-preview', 'Design preview for a Longview front yard, not a finished build', 'more', 1),
 ('white-oak-flagstone-patio-base-compaction', 'Compacting the patio base', 'whiteoak', 0),
 ('white-oak-flagstone-patio-elevated-corner', 'Chopped stone corner where the yard drops', 'whiteoak', 0),
 ('white-oak-flagstone-patio-sand-setting-bed', 'Sand setting bed', 'whiteoak', 0),
 ('white-oak-flagstone-patio-mortared-joints', 'Flagstone set and mortared around the fire pit', 'whiteoak', 0),
 ('white-oak-flagstone-patio-backfill-grade', 'Backfill and grade', 'whiteoak', 0),
 ('st:pat_004', 'Track loader on the elevated corner', 'whiteoak', 0),
 ('st:pat_008', 'Shoveling sand for the setting bed', 'whiteoak', 0),
 ('st:pat_025', 'Elevated corner of the patio', 'whiteoak', 0),
 ('st:pat_034', 'Chopped stone wall under the patio', 'whiteoak', 0),
 ('driveway-retaining-wall-block-install-2', 'Setting block course by course', 'driveway', 0),
 ('driveway-retaining-wall-base-drainage', 'Base, drainage fabric and pipe behind the wall', 'driveway', 0),
 ('driveway-retaining-wall-block-install', 'Curved run going up', 'driveway', 0),
 ('checkerboard-paver-patio-paver-layout', 'Laying out the checkerboard', 'checker', 0),
 ('checkerboard-paver-patio-install-progress-2', 'Setting pavers', 'checker', 0),
 ('checkerboard-paver-patio-base-prep', 'Compacting the patio base', 'checker', 0),
 ('flagstone-patio-flagstone-install-progress', 'Flagstone going in', 'flagstone', 0),
 ('flagstone-patio-crushed-stone-base', 'Crushed stone base, leveled', 'flagstone', 0),
 ('retaining-wall-wood-to-block-east-texas-block-install', 'First courses with drain pipe behind', 'woodwall', 0),
 ('retaining-wall-wood-to-block-east-texas-excavation-base', 'Gravel drainage base', 'woodwall', 0),
 ('st:mow_011', 'Mowing a route', 'lawn', 0),
 ('st:mow_037', 'Edging the walk', 'lawn', 0),
 ('st:mow_022', 'Blowing off the walks', 'lawn', 0),
 ('st:mow_055', 'Zero-turn mowing a backyard', 'lawn', 0),
 ('st:mow_003', 'Unloading the stand-on mower', 'lawn', 0),
 ('st:mow_043', 'Trimming along the house', 'lawn', 0),
 ('img-3454', 'Bringing flagstone in with the loader', 'more', 0),
 ('img-3680', 'Patio mid-install', 'more', 0),
 ('img-3683', 'Flagstone on a covered pad', 'more', 0),
 ('img-3452', 'Drain tubing going in', 'more', 0),
 ('1', 'Planting dianthus and pansies', 'more', 0),
]
